### ISSUE TITLE
🔴 Devise: Authentication failure

### ISSUE THREAD

**Issue by Danrod16** [Danrod16/equinox_admin#115]
<img width="1440" alt="Screenshot 2022-12-08 at 12 30 01" src="https://user-images.githubusercontent.com/26765551/206356824-6e885bf0-c790-495c-8cb4-a6ff592fdea3.png">

The authentication failure throws an error instead of redirecting ti :new. ❌

**Comment by christinasugiono** [comment]
use lvh.me:3000 instead of localhost
